[[redirects]]
  from = "/brevo-signup"
  to = "https://4a990c74.sibforms.com/serve/MUIFAINoFkxyCcSykJw2vQFAseR7-cGh2VLmJhiYPZoPxBbhnaTqwYy54h8PsQqopVL3sUbQJrToc2TpY8kZs2JUXM7foeZ8gW7fMfs8vOSNZlU2ELONvWwU5sYHa5xiGJx-REWQkDU4qtRNzHU8hCI2HXomqe5rH5FjQBiifoL2bhrOoekDyJE-hZQ2nGr9F-r_X1sAaGBXOJ8V"
  status = 200

[[redirects]]
  from = "/vbs"
  to = "https://sites.google.com/view/eagle-valley-vbs"
  status = 200
