[[redirects]]
  from = "/brevo-signup"
  to = "https://4a990c74.sibforms.com/serve/MUIFANtNkOxzjFdf_zQao6J7zgZB4K9LtM021YhriuZ--mDeY9bngap_6Sc45Z7fMo6hmd3HYf3LcFDb05ARfsQjeJuhVS26QVXkAu3Z9K_Q8A1AADC5zyewVT1r5cbaYQRYgReOMyskzE3j1cfR4Sm0w9BlpRZJHFjteoPcLx3tx6PYI0_1Uqy_weOA7MKASsJ_ehoToQaw8w2B"
  status = 200
