[[redirects]]
  from = "/brevo-signup"
  to = "https://4a990c74.sibforms.com/serve/MUIFACujAmrAzQLnu3x4ZA5SQSC9TtizBA7NJtFQO9dOWQ-6a_VAp_cAPi5qiRHzoTadGXPhYPSRmcS5q40dJfuMe791QV32ZYb8xuXC0cNJV6Z8CuvcCg6-2vonoQ0A1C2jrdM_9UmnRDL5PpYybdE2aRe3DM4LB0QbWdQ_dQgDBaRggPoCazRia1owiN5BHl8UwhzOzpFdgVXG"
  status = 200
