[[redirects]]
  from = "/brevo-signup"
  to = "https://4a990c74.sibforms.com/serve/MUIFAN0x_s5xAboi-Ln-zccbAAOdWwlxOoDbeKdyXcTuRypYy1dpN6FIWlran_u89R2wQMABPE_K2o4T9M0H85956TlhhRtRZRHoSQ9kzPUoz2l8UPUTWS1xOFge-hcTEdSzNL1FBai9ghl_t_me6rasKRaPCGZmadwesp-zTl_2Sv8_poYeKmWbPqosciAA7Qd5ng2d1PirZglO"
  status = 200
