[[redirects]]
  from = "/VBS"
  to = "https://sites.google.com/view/eagle-valley-vbs"
  status = 302

[[redirects]]
  from = "/vbs"
  to = "https://sites.google.com/view/eagle-valley-vbs"
  status = 302
